dist: trusty
sudo: false

language: scala

scala:
  - 2.12.10
  - 2.13.1

jdk:
  - openjdk11

script: sbt --warn ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "Ak1TeOrpOhU7Lqwy10qBszD9pV8ac2jGu2h7RXYjnwFz0+UbORniJu4QWskehCHpEMrUiaMzKVnPiwmG2bhRyuW/fCUvz24Hgk9EfAf24XD9p+OaXSTwXjJPNb7rA8Ngj38xKo56W99mil8xsYO5+Lcqz4KmMISRLPbrwE4QkcI5TH29iS9lMxHRr8k71Zt2cBwhfa0gEEEgs9TFXzq/K0uTXm9Vmf/dY2CiV3iD2+1mErJuwFR1HILW7dUoqoFyf/mLlpYDoNtKmMHKuVOVQKHdFEPDJGthn87IXvi597VAscO/l5vRLHfsiRBYGlyomq6fDndHeF/OPAdVvDD23YDOBU4e71jeMc0zYFmPN7FLFTVHPSHxGKbPAW0nhsXyGqmTx+67H4bDhF/ReIlYhXIiqNeUjLUD/wzhRA1kBr5ht8Q9B6opeZKMxqxgFwx9FsFKCjqHWH/Nxx+Qj6MdAQv6K+4RKJ7L12KnvN3y8EWrt+HVMZOkqXNPeY3vhW4VcaOEDObWT6eobL/WN/nfW7WkymoELYHnaYbkiROBJtZ28sXv+JElQxOT/lVnuMBfGF8jwwUSLnCGpGgyy1imTF05hZ4a08rD3uUc5Tfmxq3hehQjYRFPzg+YThKlQAeNhF/Mpjr8Z8NZ+tCvw7m0sxMOp0qSo82dXb4sd7NO+KA="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete